@startuml

package "Admin frontend" as fe
{
    package "Web pages" as pages
    {
        class "Login page" as fe_page_login
        {

        }

        class "Inhaler list page" as fe_page_inhalers
        {

        }

        class "Add inhaler page" as fe_page_add
        {

        }

        class "Edit inhaler page" as fe_page_edit
        {

        }
    }

    class "Admin API client" as fe_admin_apiclient
    {

    }

    class "User API client" as fe_user_apiclient
    {

    }
}

package "Backend" as be
{
    interface "User API endpoint" as be_userapi
    {
        GET /inhalers(query: InhalerQuery) : Inhalers
    }

    interface "Admin API endpoint" as be_adminapi
    {
        POST /admin (query: AdminQuery) : Admin
        PUT /admin (query: AdminQuery) : Admin
        DELETE /admin (query: AdminQuery) : Admin
    }
}

'Layout arrows
fe_page_inhalers -[hidden]d- fe_page_login
fe_page_login -[hidden]d- fe_page_add
fe_page_add -[hidden]d- fe_page_edit

fe_user_apiclient -[hidden]d- fe_admin_apiclient

be_userapi -[hidden]d- be_adminapi

'UML relations
fe_page_inhalers .r.> fe_user_apiclient : <<use>>

fe_page_login .r.> fe_admin_apiclient : <<use>>
fe_page_add .r.> fe_admin_apiclient : <<use>>
fe_page_edit .r.> fe_admin_apiclient : <<use>>

fe_admin_apiclient .r.> be_adminapi : <<use>>
fe_user_apiclient .r.> be_userapi : <<use>>

@enduml